# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 12:55
from __future__ import unicode_literals

import datetime
from datetime import timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0039_paiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 10, 9, 12, 55, 36, 155848, tzinfo=timezone.utc), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
