# Generated by Django 4.2.30 on 2026-09-04 17:49

from django.db import migrations, models
import libreosteoweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('libreosteoweb', '0055_alter_patient_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to=libreosteoweb.models.chemin_de_stockage_du_document),
        ),
    ]
