# Generated by Django 4.2.30
# Garde ajoutée à la main avant l'AddConstraint : la migration refuse de s'appliquer sur
# un parc qui porte des doublons, plutôt que de les réparer. Choisir lequel de deux
# dossiers patient survit n'est pas une décision de migration : ce sont des données de
# santé. Le message ne cite aucun nom propre — un journal de conteneur n'est pas l'endroit
# où déverser un état civil.

from django.core.management.base import CommandError
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower

import django.db.models.functions.text


def refuser_si_doublons(apps, schema_editor):
    Patient = apps.get_model("libreosteoweb", "Patient")
    groupes = list(
        Patient.objects.annotate(nom=Lower("family_name"), prenom=Lower("first_name"))
        .values("nom", "prenom", "birth_date")
        .annotate(nombre=Count("id"))
        .filter(nombre__gt=1)
        .order_by()
    )
    if not groupes:
        return
    identifiants = []
    for groupe in groupes:
        identifiants.extend(
            Patient.objects.annotate(
                nom=Lower("family_name"), prenom=Lower("first_name")
            )
            .filter(
                nom=groupe["nom"],
                prenom=groupe["prenom"],
                birth_date=groupe["birth_date"],
            )
            .order_by("id")
            .values_list("id", flat=True)
        )
    liste = ", ".join(str(i) for i in identifiants)
    raise CommandError(
        "Migration refusée : la base contient %d triplet(s) (nom, prénom, date de "
        "naissance) en double sans tenir compte de la casse, que la nouvelle contrainte "
        "d'unicité interdit. Patients concernés (identifiants) : %s. Aucun dossier n'est "
        "fusionné ni supprimé automatiquement : ce sont des données de santé, la "
        "résolution est manuelle. Pour les lister : SELECT id, family_name, first_name, "
        "birth_date FROM libreosteoweb_patient WHERE id IN (%s) ORDER BY "
        "lower(family_name), lower(first_name), birth_date, id;"
        % (len(groupes), liste, liste)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("libreosteoweb", "0056_alter_document_document_file"),
    ]

    operations = [
        migrations.RunPython(refuser_si_doublons, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("family_name"),
                django.db.models.functions.text.Lower("first_name"),
                models.F("birth_date"),
                name="unique_patient_nom_prenom_naissance",
            ),
        ),
    ]
