# Generated by Django 4.2.30
# Garde ajoutée à la main avant les AlterField. PostgreSQL applique ces AlterField par un
# ALTER COLUMN … TYPE numeric(10,2) USING …, qui arrondit au centime toute valeur stockée
# qui n'y était pas déjà : c'est le but, et refuser de migrer pour cela ne laisserait
# aucune issue à l'exploitant. La garde journalise donc les lignes qui vont bouger, et
# n'échoue que sur un dépassement de capacité, seul cas qui ait une correction possible.

import logging
from decimal import ROUND_HALF_UP, Decimal

from django.core.management.base import CommandError
from django.db import migrations, models

logger = logging.getLogger(__name__)

CAPACITE = 10**8
MODELES = ("Invoice", "Paiment", "OfficeSettings")


def _arrondi_comme_postgresql(montant):
    """Reproduit l'arrondi que fait le cast interne `float8 -> numeric` de PostgreSQL,
    pas celui de `round()`.

    Correction du 2026-09-05 (revue finale du lot D3) : `round(montant, 2)` arrondit sur
    la valeur binaire exacte du flottant (17 chiffres significatifs), alors que
    `float8_numeric()` -- la fonction que PostgreSQL invoque pour ce même cast -- formate
    d'abord la valeur sur 15 chiffres significatifs avant d'arrondir, perte de precision
    verifiee empiriquement contre PostgreSQL 16 :
    `99999999.99499996::float8::numeric(10,2)` y leve « numeric field overflow », alors
    que `round(99999999.99499996, 2)` rend `99999999.99` en Python -- une garde qui
    comparait cette valeur-la laissait passer une ligne que l'ALTER COLUMN refuse. Le
    formatage `%.15g` puis l'arrondi `ROUND_HALF_UP` reproduisent le meme resultat que
    PostgreSQL sur les cas verifies (valeur limite ci-dessus, une valeur juste en
    dessous, une valeur negative symetrique, un `.5` ordinaire).
    """
    return Decimal("%.15g" % montant).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def controler_les_montants(apps, schema_editor):
    hors_capacite = []
    a_arrondir = []
    for nom in MODELES:
        modele = apps.get_model("libreosteoweb", nom)
        for identifiant, montant in modele.objects.exclude(amount=None).values_list(
            "id", "amount"
        ):
            arrondi = _arrondi_comme_postgresql(montant)
            if abs(arrondi) >= CAPACITE:
                hors_capacite.append("%s#%s" % (nom, identifiant))
            elif arrondi != montant:
                a_arrondir.append("%s#%s" % (nom, identifiant))
    if a_arrondir:
        logger.warning(
            "Passage des montants en numeric(10,2) : %d valeur(s) stockée(s) à plus de "
            "deux décimales vont être arrondies au centime. Lignes concernées : %s.",
            len(a_arrondir),
            ", ".join(a_arrondir),
        )
    if hors_capacite:
        raise CommandError(
            "Migration refusée : %d montant(s) dépassent la capacité de "
            "numeric(10,2), qui borne la valeur absolue à %d. Lignes concernées : %s. "
            "Corriger ces valeurs (elles ne sont pas des honoraires plausibles), puis "
            "relancer l'instance ; aucun montant n'a été modifié."
            % (len(hors_capacite), CAPACITE, ", ".join(hors_capacite))
        )


class Migration(migrations.Migration):
    dependencies = [
        ("libreosteoweb", "0057_patient_unique_patient_nom_prenom_naissance"),
    ]

    operations = [
        migrations.RunPython(controler_les_montants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="officesettings",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=10,
                null=True,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="paiment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Amount"
            ),
        ),
    ]
