# Generated by Django 5.2.17 on 2026-09-07 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "libreosteoweb",
            "0058_alter_invoice_amount_alter_officesettings_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-date", "-id"]},
        ),
    ]
